
server:
  port: 9050
spring:
  kafka:
    consumer:
      bootstrap-servers: 0.0.0.0:9092
     
      auto-offset-reset: earliest
      
     
      
    listener:
      missing-topics-fatal: false
      
      
      
spring.cloud.stream:
  function.definition: recieve
  
  bindings:
    recieve-in-0:
      destination: rabitoo
      group: myQ
      binder: rabbit
  
#spring.application.name: rabbitmq-reciever
  